## 06 ``numpy.array`` 合并和分割

In [5]:
import numpy as np

###  合并

### ``np.concatenate``函数有两点要求：
* 相同维度的数组，
* 除了axis(0：行，1：列)外，数组的其余维度对应相等。

In [6]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [7]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [8]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [14]:
z.reshape(1, -1)

array([[666, 666, 666]])

In [36]:
#axis=0时，按行合并，垂直合并，所以要保证两个矩阵的列数一样
np.concatenate([A, np.full((5,3),99)], axis=0) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [37]:
np.concatenate([A, np.full((2,5),99)], axis=1) #axis=1时，按列合并，水平合并，所以要保证两个矩阵的行数一样

array([[ 1,  2,  3, 99, 99, 99, 99, 99],
       [ 4,  5,  6, 99, 99, 99, 99, 99]])

In [10]:
np.vstack([A, z]) #垂直合并，相当于np.concatenate([A, z], axis=0) 

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [11]:
B = np.full((2,2), 100)

In [12]:
np.hstack([A, B]) #水平合并 ，，相当于np.concatenate([A, B], axis=1) 

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [13]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### ``numpy.array`` 的分割

In [38]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x1, x2, x3 = np.split(x, [3, 7]) #用元素array中的3, 7分割，每个分割数组尾部不包含分割点的元素

In [16]:
x1

array([0, 1, 2])

In [17]:
x2

array([3, 4, 5, 6])

In [18]:
x3

array([7, 8, 9])

In [19]:
x1, x2 = np.split(x, [5])

In [20]:
x1

array([0, 1, 2, 3, 4])

In [21]:
x2

array([5, 6, 7, 8, 9])

In [66]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
A1, A2 = np.split(A,[1]) #对于一个矩阵来说，[1]表示从第二行开始分割

In [95]:
A1

array([[0, 1, 2, 3]])

In [88]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
A1, A2 = np.split(A, [2], axis=1) #对于一个矩阵来说，[2]表示从第三列开始分割

In [98]:
A1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [40]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [25]:
upper, lower = np.vsplit(A, [2]) #垂直方向分割 ，相当于split方法axis=0

In [26]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
left, right = np.hsplit(A, [2]) #水平方向分割 ，相当于split方法axis=1

In [29]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [30]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [31]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
X, y = np.hsplit(data, [-1]) #-1表示把最后一列分割出来，前半部分不包含最后一列，后半部分就是最后一列了

In [33]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [34]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [35]:
y[:, 0] #行取任意值，列取第一列，将y转换成一维数组

array([ 3,  7, 11, 15])