## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)
x

array([ 0.73576927, -1.55930789,  3.12370723, ..., -0.49249081,
       -1.73105511,  0.43395215])

### 索引

In [3]:
np.argmin(x) #获取x向量中最小元素的索引

588478

In [4]:
x[886266]

0.1353202193846307

In [5]:
np.min(x)

-4.873265973439905

In [6]:
np.argmax(x) #获取x向量中最大元素的索引

293400

In [7]:
x[4851]

-0.619447916994752

In [8]:
np.max(x)

4.965388190616637

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x) # 打乱
x

array([15, 12,  4, 13, 14, 11, 10,  9,  8,  2,  0,  6,  5,  3,  1,  7])

In [11]:
np.sort(x) #这个排序不会影响x原有元素的位置

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([15, 12,  4, 13, 14, 11, 10,  9,  8,  2,  0,  6,  5,  3,  1,  7])

In [13]:
x.sort() #直接在x调用sort后，x中元素的位置会改变

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[3, 0, 5, 2],
       [0, 3, 2, 1],
       [6, 5, 3, 9],
       [7, 4, 6, 9]])

In [16]:
np.sort(X, axis=0) #垂直排序

array([[0, 0, 2, 1],
       [3, 3, 3, 2],
       [6, 4, 5, 9],
       [7, 5, 6, 9]])

In [17]:
np.sort(X, axis=1)   #水平排序    

array([[0, 2, 3, 5],
       [0, 1, 2, 3],
       [3, 5, 6, 9],
       [4, 6, 7, 9]])

#### 使用索引

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)

In [20]:
x

array([ 9,  6, 14, 11,  5, 12, 10,  3,  2,  4,  0,  8, 13,  1,  7, 15])

In [21]:
#注意argsort返回的是索引
np.argsort(x) 

array([10, 13,  8,  7,  9,  4,  1, 14, 11,  0,  6,  3,  5, 12,  2, 15],
      dtype=int64)

In [22]:
np.partition(x, 3) #按元素3来划分切片，1，0,2会跑到3的前面

array([ 0,  1,  2,  3,  4,  8,  7,  6,  5,  9, 10, 12, 13, 11, 14, 15])

In [23]:
np.argpartition(x, 3) #np.partition()方法是返回切分后的元素，而argpartition()是返回切分元素的索引

array([10, 13,  8,  7,  9, 11, 14,  1,  4,  0,  6,  5, 12,  3,  2, 15],
      dtype=int64)

In [24]:
Y = ["{}:{}".format(i,x[i])  for i in np.argpartition(x, 3)] #“索引：元素”
Y   

['10:0',
 '13:1',
 '8:2',
 '7:3',
 '9:4',
 '11:8',
 '14:7',
 '1:6',
 '4:5',
 '0:9',
 '6:10',
 '5:12',
 '12:13',
 '3:11',
 '2:14',
 '15:15']

In [25]:
X

array([[3, 0, 5, 2],
       [0, 3, 2, 1],
       [6, 5, 3, 9],
       [7, 4, 6, 9]])

In [26]:
np.argsort(X, axis=1)

array([[1, 3, 0, 2],
       [0, 3, 2, 1],
       [2, 1, 0, 3],
       [1, 2, 0, 3]], dtype=int64)

In [29]:
np.argpartition(X, 2, axis=1)

array([[1, 3, 0, 2],
       [0, 3, 2, 1],
       [2, 1, 0, 3],
       [1, 2, 0, 3]], dtype=int64)