## 05 ``numpy.array`` 基本操作

In [2]:
import numpy as np
np.random.seed(0)

x = np.arange(10) #[起始值=0，终止值=10) 步长为1的数组

In [2]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape((3, 5)) #用arange(15)数组，构造一个3行5列的矩阵

In [4]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [5]:
x.ndim #是一个几维数组

1

In [6]:
X.ndim

2

In [7]:
x.shape #返回数组的形状

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size #返回数组的尺寸，二维数组元素个数=行*列

10

In [10]:
X.size

15

### ``numpy.array`` 的数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1] #-1代表最后一个元素

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0] # 不建议！

0

In [16]:
X[0, 0]

0

In [17]:
X[0, -1]

4

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[0:5] #切片=[0,5）

array([0, 1, 2, 3, 4])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2] #切片的步长为2

array([0, 2, 4, 6, 8])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
# 先从X中取出两行，再在这个基础上取3行，因为最多只有两行
# 所以最后只能取到两行
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [25]:
X[::-1, ::-1] #::-1表示倒序

array([[14, 12, 10,  8],
       [ 6,  4,  2,  0]])

In [29]:
C=[i for i in range(10)]
C[3:0:-1] #从第3个元素倒序排序

[3, 2, 1]

In [31]:
X[0, :]

array([0, 1, 2, 3, 4])

In [32]:
X[:, 0]

array([ 0,  5, 10])

### Subarray of ``numpy.array``

In [33]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100  #subX 和X共享一组数据，使用X(...).copy()方法会创建一个新的
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X #X的第一个元素被subX修改了

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [27]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subX = X[:2, :3].copy() #拷贝出一个新的

In [39]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
X #subX没有修改X中的元素

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape 用已有元素构建出一个新的矩阵，新构造出来的矩阵元素个数必须等于原数组的个数

In [41]:
x.shape

(10,)

In [42]:
x.ndim

1

In [43]:
x.reshape(2, 5) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
B = x.reshape(1, 10) #构建一个1行10列的数组
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
B.ndim

2

In [49]:
B.shape

(1, 10)

In [30]:
x.reshape(-1, 10) #不关心行，填充10列

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
x.reshape(10, -1) #填充10行，不关心列

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [32]:
x.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 20 into shape (3,newaxis)

In [18]:
A = np.array([[ 5,  1],
           [ 2,  3],
           [ 4,  5]
     ])
B =  np.array([[9,  1],
           [ 3, 5] ,
           [ 7, 9]
     ])
C = np.array([1,2,3])
A.T.dot(B) == B.T.dot(A) 

array([[ True, False],
       [False,  True]])