## 08 ``Numpy`` 中的聚合操作

### sum

In [18]:
import numpy as np
#产生100个[0,1)范围内的随机数
L = np.random.random(100)
sum(L)

51.990635735730365

In [19]:
np.sum(L)

51.99063573573037

In [20]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

120 ms ± 751 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.43 ms ± 27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### min, max

In [21]:
np.min(big_array)

1.1400600463673527e-08

In [22]:
np.max(big_array)

0.9999996687172112

In [23]:
big_array.min()

1.1400600463673527e-08

In [24]:
big_array.max()

0.9999996687172112

In [25]:
big_array.sum()

500178.60399336397

### 多维度聚合

In [26]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.sum(X)

120

In [28]:
np.sum(X, axis=0) #垂直相加

array([24, 28, 32, 36])

In [29]:
np.sum(X, axis=1)  #水平相加

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [33]:
np.prod(X) #矩阵X所有元素都相乘

16

In [16]:
np.prod(X + 1) #加1后再相乘

NameError: name 'X' is not defined

In [15]:
np.mean(X) #求平均值

7.5

In [16]:
np.median(X) #求中位数

7.5

In [16]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [17]:
np.median(v)

2.0

####  $\color{red}{ percentile()是求百分位的，给定一个数组，和百分比，就能求出，数组中有百分之多少的元素是小于某个数的}$ 

In [18]:
np.percentile(big_array, q=50)

2.0

In [19]:
np.percentile(v, q=50) #小于2的元素占v中百分之 50 相当于np.median(big_array)

2.0

In [21]:
np.percentile(big_array, q=100) #相当于np.max(big_array)

0.99999686126703025

In [21]:
for percent in [0, 25, 50, 75, 100]: #百分位分别是0, 25, 50, 75, 100的元素各是多少
    print(np.percentile(big_array, q=percent))

4.1243560344739194e-07
0.24990965673480173
0.4997419782068165
0.749935496211839
0.9999995503981135


In [24]:
np.var(big_array)  #求样本的方差

0.083379660489048227

In [25]:
np.std(big_array) #求样本的标准差

0.28875536443336985

In [26]:
x = np.random.normal(0, 1, 1000000) #产生多个标准正态分布样本

In [27]:
np.mean(x) #正态分布样本的均值，接近0

-0.00044876833100538597

In [28]:
np.std(x)  #标准正态分布的标准差，接近1

1.0000457010611321